name: helper_animation
description: A simple animation helper library for Flutter widgets.
version: 0.1.2
homepage: https://github.com/Greek-Cp/helper_animation
repository: https://github.com/Greek-Cp/helper_animation
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0  
  flame_audio: ^2.10.7
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/bgm/
    - assets/sounds/click/
    - assets/sounds/sfx/
    - assets/sounds/notification/
# This section declares that flame_audio is exported to consumers of your package
export:
  flame_audio: ^2.10.7
  shared_preferences: ^2.5.3

