name: helper_animation
description: A simple animation helper library for Flutter widgets.
version: 0.1.0
homepage: https://github.com/Greek-Cp/helper_animation
repository: https://github.com/Greek-Cp/helper_animation
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/bgm/
    - assets/sounds/click/
    - assets/sounds/notification/
    - assets/sounds/sfx/